<a href="https://colab.research.google.com/github/harishkumar77/ML_20BRS1231/blob/main/20BRS1231_MLLAB_6_TEST_TRAIN_SVM_ipnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

1. Importing test dataset

In [ ]:
test = pd.read_csv("/content/test (1).csv")
test.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.39              131      21            8         220    171   
1   2   8.77              118      86            7         265    114   
2   3   6.89              129      69           10         289    110   
3   4   7.96              157      53            0         403    124   
4   5   7.57              112      88            2         243     99   

  Location  Age  Education Urban   US  
0     Good   29         14   Yes  Yes  
1     Good   52         15    No  Yes  
2   Medium   50         16    No  Yes  
3      Bad   58         16   Yes   No  
4   Medium   62         11   Yes  Yes

2. Importing train dataset

In [ ]:
train = pd.read_csv("/content/train (1).csv")
train.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.01              131      29           11         335    127   
1   2   6.50              148      51           16         148    150   
2   3   7.70              118      71           12          44     89   
3   4   7.78               86      54            0         497     64   
4   5  11.82              113      66           16         322     74   

  Location  Age  Education Urban   US  
0      Bad   33         12   Yes  Yes  
1   Medium   58         17    No  Yes  
2   Medium   67         18    No  Yes  
3      Bad   33         12   Yes   No  
4     Good   76         15   Yes  Yes

In [ ]:
test['Location'] = test['Location'].astype('category')
test['Loc_category'] = test['Location'].cat.codes

test['Urban'] = test['Urban'].astype('category')
test['Urban_category'] = test['Urban'].cat.codes

test['US'] = test['US'].astype('category')
test['US_category'] = test['US'].cat.codes

test.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.39              131      21            8         220    171   
1   2   8.77              118      86            7         265    114   
2   3   6.89              129      69           10         289    110   
3   4   7.96              157      53            0         403    124   
4   5   7.57              112      88            2         243     99   

  Location  Age  Education Urban   US  location_encoded  us_encoded  \
0     Good   29         14   Yes  Yes                 1           1   
1     Good   52         15    No  Yes                 1           1   
2   Medium   50         16    No  Yes                 2           1   
3      Bad   58         16   Yes   No                 0           0   
4   Medium   62         11   Yes  Yes                 2           1   

   Urban_encoded  Loc_category  Urban_category  US_category  
0              1             1               1            1  
1              0             1               0            1  
2              0             2               0            1  
3              1             0               1            0  
4              1             2               1            1

In [ ]:
category = pd.cut(test.Sales,bins=[0,5,10,50],labels=['1','2','3'])
test.insert(1,'Class',category)

n_test = test.drop(['Sales','Location','US'],axis=1)
n_test = n_test.dropna()
n_test.head()

ID Class  CompetitorPrice  Income  Advertising  Population  Price  Age  \
0   1     2              131      21            8         220    171   29   
1   2     2              118      86            7         265    114   52   
2   3     2              129      69           10         289    110   50   
3   4     2              157      53            0         403    124   58   
4   5     2              112      88            2         243     99   62   

   Education Urban  location_encoded  us_encoded  Urban_encoded  Loc_category  \
0         14   Yes                 1           1              1             1   
1         15    No                 1           1              0             1   
2         16    No                 2           1              0             2   
3         16   Yes                 0           0              1             0   
4         11   Yes                 2           1              1             2   

   Urban_category  US_category  
0               1            1  
1               0            1  
2               0            1  
3               1            0  
4               1            1

In [ ]:
t = n_train.drop(['ID', 'Class'], axis = 1)
y_test = n_train['Class'].values

t.head()

CompetitorPrice  Income  Advertising  Population  Price  Age  Education  \
0              131      29           11         335    127   33         12   
1              148      51           16         148    150   58         17   
2              118      71           12          44     89   67         18   
3               86      54            0         497     64   33         12   
4              113      66           16         322     74   76         15   

   location_encoded  us_encoded  Urban_encoded  Loc_category  Urban_category  \
0                 0           1              1             0               1   
1                 2           1              0             2               0   
2                 2           1              0             2               0   
3                 0           0              1             0               1   
4                 1           1              1             1               1   

   US_category  
0            1  
1            1  
2            1  
3            0  
4            1

3. Forming a new column for location,US,Urban to numbers and naming it as location_encoded,us_encoded and urban_encoded

In [ ]:
train['Location'] = train['Location'].astype('category')
train['Loc_category'] = train['Location'].cat.codes

train['Urban'] = train['Urban'].astype('category')
train['Urban_category'] = train['Urban'].cat.codes

train['US'] = train['US'].astype('category')
train['US_category'] = train['US'].cat.codes

train.head()

ID Class  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1     2   6.01              131      29           11         335    127   
1   2     2   6.50              148      51           16         148    150   
2   3     2   7.70              118      71           12          44     89   
3   4     2   7.78               86      54            0         497     64   
4   5     3  11.82              113      66           16         322     74   

  Location  Age  Education Urban   US  location_encoded  us_encoded  \
0      Bad   33         12   Yes  Yes                 0           1   
1   Medium   58         17    No  Yes                 2           1   
2   Medium   67         18    No  Yes                 2           1   
3      Bad   33         12   Yes   No                 0           0   
4     Good   76         15   Yes  Yes                 1           1   

   Urban_encoded  Loc_category  Urban_category  US_category  
0              1             0               1            1  
1              0             2               0            1  
2              0             2               0            1  
3              1             0               1            0  
4              1             1               1            1

4. Removing location, urban , us and id which we dont need anymore and naming the removed dataset as n_train

In [ ]:
category = pd.cut(train.Sales,bins=[0,5,10,50],labels=['1','2','3'])
n_train = train.drop(['Sales','Location','Urban','US'],axis=1)
n_train = n_train.dropna()
n_train.head()

ID Class  CompetitorPrice  Income  Advertising  Population  Price  Age  \
0   1     2              131      29           11         335    127   33   
1   2     2              148      51           16         148    150   58   
2   3     2              118      71           12          44     89   67   
3   4     2               86      54            0         497     64   33   
4   5     3              113      66           16         322     74   76   

   Education  location_encoded  us_encoded  Urban_encoded  Loc_category  \
0         12                 0           1              1             0   
1         17                 2           1              0             2   
2         18                 2           1              0             2   
3         12                 0           0              1             0   
4         15                 1           1              1             1   

   Urban_category  US_category  
0               1            1  
1               0            1  
2               0            1  
3               1            0  
4               1            1

5. Forming a new column for location,US,Urban to numbers and naming it as location_encoded,us_encoded and urban_encoded in test dataset

In [ ]:
T = n_train.drop(['ID', 'Class'], axis = 1)
y_train = n_train['Class'].values

T.head()

CompetitorPrice  Income  Advertising  Population  Price  Age  Education  \
0              131      29           11         335    127   33         12   
1              148      51           16         148    150   58         17   
2              118      71           12          44     89   67         18   
3               86      54            0         497     64   33         12   
4              113      66           16         322     74   76         15   

   location_encoded  us_encoded  Urban_encoded  Loc_category  Urban_category  \
0                 0           1              1             0               1   
1                 2           1              0             2               0   
2                 2           1              0             2               0   
3                 0           0              1             0               1   
4                 1           1              1             1               1   

   US_category  
0            1  
1            1  
2            1  
3            0  
4            1

6. Removing location, urban , us and id which we dont need anymore and naming the removed dataset as n_test

In [ ]:
T

CompetitorPrice  Income  Advertising  Population  Price  Age  Education  \
0                131      29           11         335    127   33         12   
1                148      51           16         148    150   58         17   
2                118      71           12          44     89   67         18   
3                 86      54            0         497     64   33         12   
4                113      66           16         322     74   76         15   
..               ...     ...          ...         ...    ...  ...        ...   
344              138      61           12         156    120   25         14   
345              130      58           19         366    139   33         16   
346              144      69           11         131    104   47         11   
347              129      76           16          58    121   69         12   
348              121      42            4         188    118   54         15   

     location_encoded  us_encoded  Urban_encoded  Loc_category  \
0                   0           1              1             0   
1                   2           1              0             2   
2                   2           1              0             2   
3                   0           0              1             0   
4                   1           1              1             1   
..                ...         ...            ...           ...   
344                 2           1              1             2   
345                 0           1              1             0   
346                 2           1              1             2   
347                 2           1              1             2   
348                 2           1              1             2   

     Urban_category  US_category  
0                 1            1  
1                 0            1  
2                 0            1  
3                 1            0  
4                 1            1  
..              ...          ...  
344               1            1  
345               1            1  
346               1            1  
347               1            1  
348               1            1  

[348 rows x 13 columns]

In [ ]:
y_train

['2', '2', '2', '2', '3', ..., '2', '2', '3', '2', '2']
Length: 348
Categories (3, object): ['1' < '2' < '3']

In [ ]:
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(T,y_train)

SVC(kernel='linear')

In [ ]:
y_test

array([ 6.39,  8.77,  6.89,  7.96,  7.57,  8.89,  7.36,  8.75,  5.94,
        7.52,  6.8 , 10.14, 11.7 ,  6.41,  4.56, 13.39,  3.89,  8.54,
       10.31, 10.06, 12.53,  2.93, 12.49,  8.65, 12.57,  4.42,  4.81,
        4.69,  4.67,  5.17, 11.19,  8.97,  5.01,  8.01,  7.44,  5.86,
        7.72, 12.98,  5.32,  4.68,  2.05,  8.78,  9.54,  8.19,  7.37,
        2.52,  3.9 , 11.48,  5.73,  8.57,  9.33])

In [ ]:
T = n_train.drop(['ID', 'Sales'], axis = 1)
y_train = n_train['Sales'].values

T.head()

CompetitorPrice  Income  Advertising  Population  Price  Age  Education  \
0              131      29           11         335    127   33         12   
1              148      51           16         148    150   58         17   
2              118      71           12          44     89   67         18   
3               86      54            0         497     64   33         12   
4              113      66           16         322     74   76         15   

   location_encoded  us_encoded  Urban_encoded  
0                 0           1              1  
1                 2           1              0  
2                 2           1              0  
3                 0           0              1  
4                 1           1              1

In [ ]:
T

CompetitorPrice  Income  Advertising  Population  Price  Age  Education  \
0                131      29           11         335    127   33         12   
1                148      51           16         148    150   58         17   
2                118      71           12          44     89   67         18   
3                 86      54            0         497     64   33         12   
4                113      66           16         322     74   76         15   
..               ...     ...          ...         ...    ...  ...        ...   
344              138      61           12         156    120   25         14   
345              130      58           19         366    139   33         16   
346              144      69           11         131    104   47         11   
347              129      76           16          58    121   69         12   
348              121      42            4         188    118   54         15   

     location_encoded  us_encoded  Urban_encoded  
0                   0           1              1  
1                   2           1              0  
2                   2           1              0  
3                   0           0              1  
4                   1           1              1  
..                ...         ...            ...  
344                 2           1              1  
345                 0           1              1  
346                 2           1              1  
347                 2           1              1  
348                 2           1              1  

[349 rows x 10 columns]

In [ ]:
y_train

array([ 6.01,  6.5 ,  7.7 ,  7.78, 11.82,  3.98,  6.64,  6.67,  7.58,
        9.24,  7.99,  3.24,  5.99,  4.36,  7.6 ,  9.44,  4.16,  0.53,
        6.67,  0.91,  8.09,  5.3 ,  9.08, 11.48,  7.49,  3.47,  5.17,
        8.67,  7.8 , 11.19,  7.5 ,  5.64,  4.42,  5.05,  5.07,  4.69,
        7.41,  4.38,  2.86,  9.32, 10.59,  8.33,  7.41,  7.8 ,  3.9 ,
        5.83, 14.37,  9.32,  8.98, 10.77, 12.44,  7.74,  3.47,  5.52,
        5.27,  9.71, 10.07,  8.77, 13.28,  3.42, 11.07,  9.4 ,  7.43,
        3.62, 15.63,  4.99,  5.3 , 12.49,  8.07,  8.32, 10.71,  7.71,
        1.82,  8.7 ,  5.55,  5.97,  5.9 ,  0.16,  2.34,  7.38,  8.67,
        8.64, 12.04,  4.2 ,  8.69,  5.57,  5.81,  7.82, 12.61,  7.62,
        5.87,  8.8 ,  6.88, 12.85,  6.88,  8.79,  6.11,  6.98,  8.74,
        5.42,  7.67,  6.1 ,  9.14,  5.47,  6.41, 10.  ,  6.53,  8.39,
       10.08,  6.63, 10.5 ,  9.53,  5.33, 11.54,  9.16,  6.03,  7.77,
       12.01,  7.02, 11.99,  7.8 , 10.43, 11.18,  5.56, 11.67,  7.23,
        9.39,  4.1 ,

In [ ]:
y_pred = svclassifier.predict(t)
print(y_pred)

['2' '2' '2' '2' '3' '1' '2' '2' '2' '2' '2' '2' '2' '1' '2' '2' '1' '1'
 '1' '1' '2' '2' '2' '2' '1' '2' '2' '2' '1' '2' '2' '2' '1' '1' '1' '2'
 '2' '2' '1' '3' '3' '2' '2' '2' '1' '2' '3' '3' '2' '2' '3' '2' '1' '2'
 '2' '2' '3' '2' '3' '2' '3' '3' '2' '1' '3' '2' '2' '3' '2' '2' '2' '2'
 '1' '2' '2' '2' '2' '1' '1' '2' '2' '2' '3' '2' '2' '2' '2' '2' '3' '2'
 '2' '2' '2' '2' '2' '3' '2' '2' '2' '2' '3' '2' '2' '2' '2' '2' '2' '3'
 '2' '2' '2' '2' '2' '2' '1' '2' '2' '3' '2' '2' '2' '3' '3' '2' '3' '2'
 '2' '1' '2' '2' '2' '2' '2' '2' '2' '3' '2' '2' '2' '2' '2' '2' '3' '3'
 '2' '2' '1' '2' '3' '2' '2' '2' '2' '2' '1' '2' '2' '1' '2' '2' '2' '2'
 '2' '1' '2' '2' '2' '2' '1' '1' '1' '2' '2' '3' '2' '2' '2' '3' '2' '2'
 '2' '2' '1' '2' '2' '2' '2' '2' '2' '3' '2' '1' '2' '2' '2' '1' '1' '2'
 '2' '3' '1' '3' '2' '2' '2' '3' '2' '1' '2' '2' '2' '2' '2' '2' '3' '1'
 '1' '2' '2' '3' '3' '2' '2' '2' '2' '2' '1' '2' '2' '2' '2' '2' '3' '2'
 '1' '3' '2' '2' '2' '2' '2' '2' '2' '2' '2' '1' '3

In [ ]:
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics._plot.confusion_matrix import plot_confusion_matrix
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test,  y_pred)
precision = precision_score(y_test,  y_pred, average='micro')
recall = recall_score(y_test, y_pred, average='micro')
f1 = f1_score(y_test,  y_pred, average='micro')

print('Confusion matrix for svm',cm)
print('Accuracy_svm: %.3f' %accuracy)
print('Precision_svm: %.3f' %precision)
print('Recall_svm: %.3f' %recall)
print('f1-score_svme: %.3f' %f1)

Confusion matrix for svm [[ 36  29   0]
 [ 14 187  15]
 [  0  31  36]]
Accuracy_svm: 0.744
Precision_svm: 0.744
Recall_svm: 0.744
f1-score_svme: 0.744
